# Site settings
title: Freeflight
email: web@freeflight.org.uk
description: "Alan Sparrow"
baseurl: ""
url: "http://freeflight.org.uk"
twitter_username: ahsparrow
github_username:  ahsparrow

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman