# Site settings
title: Freeflight
email: web@freeflight.org.uk
description: "Alan Sparrow's website. Navplot and other things."
baseurl: ""
url: "http://www.freeflight.org.uk"
twitter_username: ahsparrow
github_username:  ahsparrow

# Build settings
markdown: kramdown
permalink: pretty
